version = 1

# Diretórios que devem ser ignorados (opcional)
exclude_patterns = [
  "node_modules/**",
  ".next/**",
  "out/**",
  "dist/**",
  "build/**",
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  # Detecta automaticamente JS/TS/React
  dialect = "typescript"
  runtime = "nodejs"

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "prettier"
enabled = true
